spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: "jdbc:mysql://localhost:3306/myschema"
    username: "root"
    password: "password"

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect

server:
  port: 8443
  ssl:
    key-store:  classpath:mykeystore.p12
    key-password: password
    key-store-password: password
    key-store-type: PKCS12 # optional
    key-alias:  tomcat # optional